<?xml version="1.0"?>
<package format="3">
  <name>agrobot_description</name>
  <version>0.1.0</version>
  <description>Agrobot rigid body, wheels and cameras.</description>
  <maintainer email="dev@todo.local">dev</maintainer>
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
