#!/bin/bash
# Скрипт для настройки DS4 driver в контейнере

echo "🎮 Настройка DS4 driver в контейнере"
echo ""
echo "Выполните следующие команды в контейнере:"
echo ""
echo "1. Создать структуру workspace:"
echo "   cd /workspace"
echo "   mkdir -p src"
echo ""
echo "2. Создать символические ссылки на DS4 пакеты:"
echo "   ln -sf ../ds4_driver_submodule/ds4_driver_msgs src/ds4_driver_msgs"
echo "   ln -sf ../ds4_driver_submodule/ds4_driver src/ds4_driver"
echo ""
echo "3. Собрать пакеты:"
echo "   colcon build --packages-select ds4_driver_msgs ds4_driver --symlink-install"
echo ""
echo "4. Загрузить окружение:"
echo "   source install/setup.zsh"
echo ""
echo "5. Проверить джойстик:"
echo "   ls -la /dev/input/js*"
echo "   ls -la /dev/input/event*"
echo ""
echo "6. Запустить DS4 driver (в одном терминале):"
echo "   ros2 launch ds4_driver ds4_twist.launch.xml"
echo ""
echo "7. В другом терминале проверить команды:"
echo "   ros2 topic echo /cmd_vel"
echo ""

